version: "3.7"
services:
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: "nacos.manager.svc.cluster.local"
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - EMBEDDED_STORAGE=embedded
    volumes:
      - ./.logs/nacos:/home/nacos/logs
      - ./.data/nacos:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s

  sentinel:
    build:
      context: .
      dockerfile: sentinel.Dockerfile
    container_name: "sentinel.manager.svc.cluster.local"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s

  mysql:
    image: mysql:5.7.37
    container_name: "mysql.manager.svc.cluster.local"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql -uroot -p${MYSQL_ROOT_PASSWORD} --execute 'select version();'" ]
